namespace HerBudget
{
    public enum SubCategoryType
    {
        RENT, INTERNET, CAR_INSURANCE, ELECTRIC, GAS_HOME, PHONES, TV, HEALTHCARE, 
        DENTAL, SAVINGS, GAS_CAR, GROCERIES, RESTAURANT, MISC_NECESSARY, MISC_UNNECESSARY
    }
}
